plugins { id 'com.android.application' }
android {
    namespace 'com.aziz.stickeratolyesi'
    compileSdk 35
    useLibrary 'android.test.runner'
    useLibrary 'android.test.base'
    defaultConfig {
        applicationId 'com.aziz.stickeratolyesi'
        minSdk 28
        targetSdk 35
        versionCode 1
        versionName '0.1.0'
        testInstrumentationRunner 'android.test.InstrumentationTestRunner'
    }
    signingConfigs {
        debug {
            storeFile rootProject.file('development.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    lint { abortOnError true; disable 'OldTargetApi', 'ObsoleteSdkInt' }
}
